### ISSUE TITLE
short form wasn't returning the ami_id and failing silently

### ISSUE THREAD

**Issue by donnoman** [terraform-community-modules/tf_aws_ubuntu_ami#12] opened 2017-01-14 00:46 UTC
```
module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_ubuntu_ami/ebs"
  region = "${var.aws_region}"
  distribution = "trusty"
  instance_type = "${var.instance_type}"
}

output "stage" {
  value = "${var.stage}"
}

output "security_group_id" {
  value = "${module.site.security_group_id}"
}

output "source_ami" {
  value = "${module.ami.ami_id}"
}

output "region" {
  value = "${var.aws_region}"
}

output "instance_type" {
  value = "${var.instance_type}"
}

data "template_file" "json_config" {
  template = <<EOF
{
  "stage": "${var.stage}",
  "security_group_id": "${module.site.security_group_id}",
  "region": "${var.aws_region}",
  "instance_type": "${var.instance_type}",
  "source_ami": "${module.ami.ami_id}"
}
EOF
}

output "json_config" {
  value = "${data.template_file.json_config.rendered}"
}
```

gets back nothing

```
Outputs:

instance_type = m2.medium
json_config =
region = us-west-2
security_group_id = sg-9ec912e6
stage = staging
```

source_ami is missing from the variable output, and no output in json_config

I switched to the long form https://github.com/terraform-community-modules/tf_aws_ubuntu_ami

```
module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_ubuntu_ami"
  region = "${var.aws_region}"
  distribution = "trusty"
  architecture = "amd64"
  virttype = "hvm"
  storagetype = "ebs"
}
```

now after much teeth gnashing I have something working

```
instance_type = m2.medium
json_config = {
  "stage": "staging",
  "security_group_id": "sg-9ec912e6",
  "region": "us-west-2",
  "instance_type": "m2.medium",
  "source_ami": "ami-6418c304"
}

region = us-west-2
security_group_id = sg-9ec912e6
source_ami = ami-6418c304
stage = staging
```

**Comment by donnoman** [comment] 2017-01-14 02:15
It could have been caused because I was specifying a m2.medium instead of t2.medium

**Comment by antonbabenko** [comment] 2017-01-14 10:41
Not a bug, closing it.

**Closed as completed by antonbabenko** 2017-01-14 10:41 UTC

**Comment by donnoman** [comment] 2017-01-14 15:55
I think failing silently is the bug, that made it very tough to uncover what the real problem was.

ref:  https://github.com/hashicorp/terraform/issues/11203
